### ISSUE TITLE
extract-text-webpack-plugin

### ISSUE THREAD

**Issue by mmahalwy** [justin808/bootstrap-sass-loader#11]
I think it'd be awesome if we can include the `extract-text-webpack-plugin` so the sass doesn't get included into a style tag.

**Comment by mmahalwy** [comment]
I take that back! It's in the comments. I will create a PR to add to Readme

**Comment by justin808** [comment]
I did a lot of work to make the extra-text-webpack-plugin work, but since I'm doing all Rails projects, it didn't seem super useful. Anyway, pull request would be great! Please be sure to either create a new example or a PR on the example. I think the example is pretty key for showing people how to use this.

**Comment by mmahalwy** [comment]
Yeah I take it back! In fact, it's in the custom config file you included as an example. I missed it for some odd reason :(

**Comment by justin808** [comment]
I found that if you're doing Rails work, it's best to leave the sass compilation up the Rails asset pipeline, especially when making fonts and images work with the sass code.

**Comment by mmahalwy** [comment]
Yes +1 on that!

On Thu, Mar 12, 2015 at 12:44 AM, Justin Gordon <notifications@github.com>
wrote:

> I found that if you're doing Rails work, it's best to leave the sass
> compilation up the Rails asset pipeline, especially when making fonts and
> images work with the sass code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/justin808/bootstrap-sass-loader/issues/11#issuecomment-78436135>
> .
>



-- 
*Mohamed El Mahallawy*



*@mmahalwy4167696068*
