### ISSUE TITLE
Wrong partials ordering

### ISSUE THREAD

**Issue by mgtitimoli** [justin808/bootstrap-sass-loader#17]
[Partials array](https://github.com/justin808/bootstrap-sass-loader/blob/master/bootstrap-sass-styles.loader.js#L1-L44) must be ordered the same as [_bootstrap.scss](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss) file present in [bootstrap-sass project](https://github.com/twbs/bootstrap-sass), since otherwise some classes override some others, causing wrong components rendering (currently glyphicon is included after forms, and this breaks the [has-feedback feature](http://getbootstrap.com/css/#forms-control-validation)).

Also I noticed, that **responsive-embed** partial is missing.

This [PR](https://github.com/justin808/bootstrap-sass-loader/pull/18) fixes this.

**Comment by justin808** [comment]
Awesome. I'll get this integrated asap!

**Comment by mgtitimoli** [comment]
Great @justin808 :+1:, many thanks!!
