### ISSUE TITLE
File to import not found or unreadable with sass-loader 1.0.3

### ISSUE THREAD

**Issue by adavkay** [justin808/bootstrap-sass-loader#23]
Hey Justin,

I'm not sure if this is a problem with your bootstrap-sass-loader or sass-loader but I thought I would let you know. My setup can be found in my repo [isomorphic-react-example](https://github.com/adavkay/isomorphic-react-example). My code base is based off of [react-starter-kit](https://github.com/kriasoft/react-starter-kit) and I run my webpack config and bundling through `gulpfile.babel.js`. 

When I attempted to bundle bootstrap with your loader and `sass-loader@1.0.3` I got the following error message: 

```
ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader!./~/sass-loader?sourceMap!./~/bootstrap-sass-loader/bootstrap-sass-styles.loader.js!./bootstrap-sass.config.js
Module build failed: ModuleBuildError: Module build failed: 
var ExtractTextPlugin = require('extract-text-webpack-plugin');
       ^
      File to import not found or unreadable: Users/akay/devel/isomorphic-react-example/node_modules/bootstrap-sass/assets/stylesheets/bootstrap/variables.scss
      in /Users/akay/devel/isomorphic-react-example/bootstrap-sass.config.js (line 1, column 9)
    at DependenciesBlock.onModuleBuildFailed (/Users/akay/devel/isomorphic-react-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/akay/devel/isomorphic-react-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/akay/devel/isomorphic-react-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/akay/devel/isomorphic-react-example/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.onRender (/Users/akay/devel/isomorphic-react-example/node_modules/sass-loader/index.js:160:13)
    at options.error (/Users/akay/devel/isomorphic-react-example/node_modules/node-sass/lib/index.js:279:32)
 @ ./~/bootstrap-sass-loader/index.loader.js!./bootstrap-sass.config.js 1:0-369
```

However, if I downgrade to `sass-loader@1.0.2` everything compiles fine.

**Comment by justin808** [comment]
I'm seeing a possibly related issue here, when using node 0.12.7: https://github.com/justin808/react-webpack-rails-tutorial/issues/52

**Comment by jorrit** [comment]
See jtangelder/sass-loader#126 . Downgrade to sass-loader 1.0.2 if the improvements of 1.0.3 don't matter for you.

**Comment by jorrit** [comment]
This would also be fixed, I think, when `addImportReturnDependency` writes a relative path instead of an absolute path, using `path.relative()`.

**Comment by geminiyellow** [comment]
@jorrit not working for me. 
this loader not working.

**Comment by mmahalwy** [comment]
@geminiyellow & @adavkay just downgrade to sass-loader 1.0.2 for now

**Comment by justin808** [comment]
@jorrit Could you file a PR if that works and works with the older version as well?

**Comment by jorrit** [comment]
Done, see #25.

**Comment by jorrit** [comment]
When I `npm link` the changed version, @mmahalwy 's code runs, even with sass-loader 1.0.3.

**Comment by mmahalwy** [comment]
@jorrit thanks for getting to that. I appreciate it!
