### ISSUE TITLE
@import scss file hot reload

### ISSUE THREAD

**Issue by f0def** [justin808/bootstrap-sass-loader#26]
Thanks for a great loader!
I using customization with bootstrap-sass.config.js like that:
```javascript
module.exports = {
  preBootstrapCustomizations: "./_pre-bootstrap-customizations.scss",
  bootstrapCustomizations: "./_bootstrap-customizations.scss",
  mainSass: "./main.scss",
  styleLoader: ExtractTextPlugin.extract("style-loader", "css-loader!sass?outputStyle=expanded"),
  scripts: {
    ...
  },
  styles: {
    ...
  }
};
```
main.scss
```sass
//some css
@import "table";
```
table.scss
```sass
//table css
```
Then i modify `main.scss` webpack recompile and reload page. But then i change imported `table.scss` nothing happens. How to fix?

**Comment by jorrit** [comment]
I think bootstrap-sass-loader relies on sass-loader for hot reload functionality, so this issue seems similar to jtangelder/sass-loader#130.

**Comment by f0def** [comment]
@jorrit thx you. Indeed, the problem in the sass-loader.
