### ISSUE TITLE
1.0.7 ERROR: Could not find path to config.bootstrapCustomizations

### ISSUE THREAD

**Issue by austinnichols101** [justin808/bootstrap-sass-loader#29]
Ref line *55* in bootstrap-sass-styles.loader.js: https://github.com/justin808/bootstrap-sass-loader/commit/eda5080fef10a49219b6fba9c4bbff3079115c1e#56

My code specifies bootstrapCustomizations of `'./app/_bootstrap.config.scss'`

In version 1.0.6, fileNameResolved is `'/home/user/my-project/app/_bootstrap.config.scss'`
In version 1.0.7, fileNameResolved is `'_bootstrap.config.scss'`

Which results in...
`ERROR: Could not find path to config.bootstrapCustomizations: _bootstrap.config.scss`

**Comment by jorrit** [comment]
This was fixed with #27.  I think a release will be made shortly.

**Comment by justin808** [comment]
Release 1.0.8

**Comment by austinnichols101** [comment]
Thank you sir!
