### ISSUE TITLE
Make mainSass optional

### ISSUE THREAD

**Issue by azamat-sharapov** [justin808/bootstrap-sass-loader#5]
Thanks for the loader!

Could you make `mainSass` in config file optional? Because there are cases, where I use different preprocessor for main stylesheet, like Stylus or plain CSS.

Thanks

**Comment by azamat-sharapov** [comment]
I could make pull request for this, if you don't mind.

**Comment by justin808** [comment]
Thanks for the feedback. Yes, please make a pull request. Are you familiar with writing loaders? This should be pretty simple.

Here's some tips on debugging: 

http://forum.railsonmaui.com/t/debugging-nodejs-and-webpack-loaders/142

**Comment by azamat-sharapov** [comment]
Well, not much familiar with webpack loader yet, began playing with webpack not long ago. But JS knowledge seems to be enough for this change :) 
Just created pull request #6, please review.

Thanks
